# Generated by Django 3.2.4 on 2021-06-24 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocks',
            options={'verbose_name_plural': 'stocks'},
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_close',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_high',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_last',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_low',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_open',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='price_prev_close',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='tottrd_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('symbol', 'date')},
        ),
    ]
